-- 003_trade_executed_at.sql
-- Adds an `executed_at` column to `trades` so the AI assistant can record
-- a trade at the historical moment the user named ("buy NVDA 3 days ago"
-- -> executed_at = 3 days ago) rather than always stamping NOW().
--
-- `trade_timestamp` remains the conceptual moment of the trade; the new
-- `executed_at` column is the row-write moment and defaults to NOW() so
-- existing call sites that don't pass it explicitly keep working.

ALTER TABLE trades
    ADD COLUMN IF NOT EXISTS executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- Backfill is implicit: the DEFAULT NOW() above only applies to new rows
-- when executed_at is not provided. Existing rows already had a value
-- generated by the default, so nothing further to do.

CREATE INDEX IF NOT EXISTS idx_trades_executed_at
    ON trades(portfolio_id, executed_at DESC);
